import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dev Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, "max-w-3xl m-auto w-[92%]")}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
